## 目的
選択肢に対して、回答があれば１、回答がない場合は０の配列を作成する

## 例
1~5までの選択肢が５つある。
選択肢の内、1と３を回答する。


In [2]:
import numpy as np

In [4]:
# 選択肢：1~5は適当な選択肢のID
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [8]:
# 1と　３は、回答したID
y = np.array([1,3])
y

array([1, 3])

In [7]:
# in1dを使うことで、存在チェックをしてくれる
np.in1d(x,y)

array([ True, False,  True, False, False], dtype=bool)

In [6]:
# 答え: astypeでbooleanからintに変換する
np.in1d(x,y).astype(int)

array([1, 0, 1, 0, 0])